window.PLAYERS_EXCEL_DATA = {
  "ALL": [
    {
      "nombre": "Martinez",
      "pj": 113,
      "pg": 55,
      "pe": 16,
      "pp": 42,
      "goles": 2,
      "asistencias": 4,
      "amarillas": 5,
      "rojas": 2,
      "mvp": 3
    },
    {
      "nombre": "Sparkov",
      "pj": 107,
      "pg": 55,
      "pe": 20,
      "pp": 32,
      "goles": 135,
      "asistencias": 24,
      "amarillas": 7,
      "rojas": 1,
      "mvp": 7
    },
    {
      "nombre": "Menchaca",
      "pj": 101,
      "pg": 52,
      "pe": 16,
      "pp": 30,
      "goles": 41,
      "asistencias": 8,
      "amarillas": 5,
      "rojas": 0,
      "mvp": 8
    },
    {
      "nombre": "Iza",
      "pj": 100,
      "pg": 49,
      "pe": 16,
      "pp": 35,
      "goles": 28,
      "asistencias": 6,
      "amarillas": 12,
      "rojas": 4,
      "mvp": 4
    },
    {
      "nombre": "Blanco",
      "pj": 93,
      "pg": 49,
      "pe": 15,
      "pp": 29,
      "goles": 7,
      "asistencias": 6,
      "amarillas": 2,
      "rojas": 0,
      "mvp": 6
    },
    {
      "nombre": "Pedemonte",
      "pj": 90,
      "pg": 48,
      "pe": 15,
      "pp": 27,
      "goles": 38,
      "asistencias": 20,
      "amarillas": 19,
      "rojas": 2,
      "mvp": 10
    },
    {
      "nombre": "Bonilla",
      "pj": 82,
      "pg": 43,
      "pe": 14,
      "pp": 25,
      "goles": 13,
      "asistencias": 7,
      "amarillas": 5,
      "rojas": 1,
      "mvp": 1
    },
    {
      "nombre": "Mateo",
      "pj": 75,
      "pg": 36,
      "pe": 13,
      "pp": 24,
      "goles": 4,
      "asistencias": 8,
      "amarillas": 1,
      "rojas": 2,
      "mvp": 0
    },
    {
      "nombre": "Anzuatte",
      "pj": 65,
      "pg": 31,
      "pe": 12,
      "pp": 22,
      "goles": 10,
      "asistencias": 4,
      "amarillas": 16,
      "rojas": 1,
      "mvp": 0
    },
    {
      "nombre": "Flores",
      "pj": 58,
      "pg": 33,
      "pe": 12,
      "pp": 13,
      "goles": 2,
      "asistencias": 0,
      "amarillas": 4,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Olarte",
      "pj": 48,
      "pg": 21,
      "pe": 5,
      "pp": 22,
      "goles": 2,
      "asistencias": 0,
      "amarillas": 3,
      "rojas": 0,
      "mvp": 2
    },
    {
      "nombre": "Colombo",
      "pj": 43,
      "pg": 25,
      "pe": 4,
      "pp": 14,
      "goles": 3,
      "asistencias": 0,
      "amarillas": 1,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Da Silveira",
      "pj": 41,
      "pg": 19,
      "pe": 10,
      "pp": 13,
      "goles": 4,
      "asistencias": 4,
      "amarillas": 7,
      "rojas": 1,
      "mvp": 0
    },
    {
      "nombre": "Dobal",
      "pj": 39,
      "pg": 19,
      "pe": 7,
      "pp": 13,
      "goles": 4,
      "asistencias": 7,
      "amarillas": 3,
      "rojas": 1,
      "mvp": 3
    },
    {
      "nombre": "Bruno Silva",
      "pj": 37,
      "pg": 22,
      "pe": 8,
      "pp": 7,
      "goles": 0,
      "asistencias": 1,
      "amarillas": 9,
      "rojas": 3,
      "mvp": 0
    },
    {
      "nombre": "Alvez",
      "pj": 32,
      "pg": 12,
      "pe": 4,
      "pp": 16,
      "goles": 2,
      "asistencias": 1,
      "amarillas": 3,
      "rojas": 0,
      "mvp": 3
    },
    {
      "nombre": "Molina",
      "pj": 25,
      "pg": 10,
      "pe": 1,
      "pp": 14,
      "goles": 1,
      "asistencias": 0,
      "amarillas": 2,
      "rojas": 0,
      "mvp": 2
    },
    {
      "nombre": "Rodriguez",
      "pj": 22,
      "pg": 15,
      "pe": 3,
      "pp": 4,
      "goles": 7,
      "asistencias": 0,
      "amarillas": 2,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Luzardo",
      "pj": 22,
      "pg": 10,
      "pe": 4,
      "pp": 8,
      "goles": 3,
      "asistencias": 1,
      "amarillas": 1,
      "rojas": 1,
      "mvp": 1
    },
    {
      "nombre": "De Leon",
      "pj": 21,
      "pg": 7,
      "pe": 2,
      "pp": 12,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 3,
      "rojas": 1,
      "mvp": 0
    },
    {
      "nombre": "Mari",
      "pj": 20,
      "pg": 9,
      "pe": 1,
      "pp": 10,
      "goles": 4,
      "asistencias": 3,
      "amarillas": 2,
      "rojas": 0,
      "mvp": 1
    },
    {
      "nombre": "Cravino",
      "pj": 17,
      "pg": 8,
      "pe": 2,
      "pp": 7,
      "goles": 8,
      "asistencias": 7,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 2
    },
    {
      "nombre": "Fernandez",
      "pj": 16,
      "pg": 6,
      "pe": 2,
      "pp": 8,
      "goles": 2,
      "asistencias": 0,
      "amarillas": 3,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Lorenzo",
      "pj": 14,
      "pg": 4,
      "pe": 2,
      "pp": 8,
      "goles": 1,
      "asistencias": 0,
      "amarillas": 1,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Brito",
      "pj": 11,
      "pg": 6,
      "pe": 1,
      "pp": 4,
      "goles": 1,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Valle",
      "pj": 9,
      "pg": 2,
      "pe": 1,
      "pp": 6,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Balestie",
      "pj": 6,
      "pg": 2,
      "pe": 0,
      "pp": 4,
      "goles": 2,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 2,
      "mvp": 0
    },
    {
      "nombre": "Vigil",
      "pj": 5,
      "pg": 2,
      "pe": 0,
      "pp": 3,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 1
    },
    {
      "nombre": "Diego Rocca",
      "pj": 4,
      "pg": 3,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Gaston Silva",
      "pj": 3,
      "pg": 1,
      "pe": 0,
      "pp": 2,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    }
  ],
  "2026": [
    {
      "nombre": "Sparkov",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 4,
      "asistencias": 2,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 2
    },
    {
      "nombre": "Mari",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 2,
      "asistencias": 1,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Iza",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 1,
      "asistencias": 0,
      "amarillas": 1,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Colombo",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 1,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Olarte",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Bonilla",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 1,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 1
    },
    {
      "nombre": "Anzuatte",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 1,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Martinez",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 1,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Menchaca",
      "pj": 3,
      "pg": 2,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 2,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Blanco",
      "pj": 2,
      "pg": 1,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Flores",
      "pj": 2,
      "pg": 2,
      "pe": 0,
      "pp": 0,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Molina",
      "pj": 1,
      "pg": 0,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "De Leon",
      "pj": 1,
      "pg": 0,
      "pe": 0,
      "pp": 1,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    },
    {
      "nombre": "Pedemonte",
      "pj": 1,
      "pg": 1,
      "pe": 0,
      "pp": 0,
      "goles": 0,
      "asistencias": 0,
      "amarillas": 0,
      "rojas": 0,
      "mvp": 0
    }
  ]
};
